### ISSUE TITLE
Day 8 : "choices" is not an option in job/create form rendering

### ISSUE THREAD

**Issue by liloo2040** [gregurco/jobeet#1]
Hi! I moved forward on the tutorial and I am currently trying to render the form JobType. 

The thing is... when I'm trying to see the result on job/create, it shows an exception at this line `$form = $this->createForm(JobType::class, $job); `

So, I have looked in the form and controller, seeing if I didn't miss any use or namespaces and and compared with your code and... it's not working.

The error says that 

> "choices" is not an option

However, when I'm going to the Symfony documentation, it is an option. I tried another way with a simple array after 'choices', but it didn't work.

Thanks in advance!

**Comment by gregurco** [comment]
Hello!
I checked your repository and found an error: https://github.com/liloo2040/jobeet/blob/dev/src/Form/JobType.php#L93 
Field with `TextType` really has no choices option.

See all TextType options here: http://symfony.com/doc/current/reference/forms/types/text.html

**Comment by liloo2040** [comment]
Hi! 

I just fixed the error! 

Thank you!
