### ISSUE TITLE
Branch tests

### ISSUE THREAD

**Issue by onlinebizsoft** [gregurco/jobeet#9]
is it meant for Jobeet Day 16: The Functional Tests ?

**Comment by gregurco** [comment]
Hello @onlinebizsoft 
Could you please reformulate your questions?

**Comment by onlinebizsoft** [comment]
I mean I can see Day 16 is functional test subject and the "tests" branch
seems to have some test codes.

**Comment by gregurco** [comment]
Yep, but it's not related to the day 16. There we tried to write some generic tests.
